version: 2

sources:
  - name: dbt_cas_final_localbike
    tables :
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name : stores